[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jbl = "FGauH3y9Qh5k98WxExrz8CVcqUA6VQuepLPRNxfuB3JH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"

[hooks]
