[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jbl = "2bnwnhWHfCSKRWgfuyjjJ19GW9vwawVDM96hTRBketph"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"

[hooks]
