[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jbl = "13u41zmNh2HykqTvh82K5vaTVTSegX9jMCFt2DqsoxLn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"

[hooks]
